### ISSUE TITLE
Linking Sensi Themostats

### ISSUE THREAD

**Issue by Pheelix** [iprak/sensi#20]
Is there any chance you could make it so we can link multiple Sensi thermostats.  So if i change the temp on one, the other one changes as well to match it?  I have a spare sensi classic, and would like to have it on the wall downstairs and just run it off batteries and not wired to the HVAC.  And spending $ each month on Sensi plan isn't something I want or anyone should do.

**Comment by iprak** [comment]
Each sensi is a separate entity at this point. I will not be able to incorporate this feature but you can do this via an automation like this. You would want to do the same for the mode.

```
  - alias: update_target_temperature
    id: update_target_temperature
    trigger:
    - platform: state
      entity_id: climate.source
      attribute: temperature
    action:
      - service: climate.set_temperature
        data:
          temperature: >-
            {{ state_attr('climate.source', 'temperature') |float }}
        target:
          entity_id: climate.target
```
